version: '3.8'
services:

  reactboard:
    image: dianaseong/reactboard:v2
    ports:
      - "9000:80"
    networks:
      - backend
    depends_on:
      - postapp


  postapp:
    image: dianaseong/postapp:v3

    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - db

  db:
    image: mysql:8.0.41
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=db_board
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend
volumes:
  db_data:
  
networks:
  backend:
    driver: bridge


     